export const cryptoCurrencies = [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    sign: '₿',
    image: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    sign: 'Ξ',
    image: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    sign: '◎',
    image: 'https://cryptologos.cc/logos/solana-sol-logo.png',
  },
  {
    id: 'xrp',
    name: 'XRP',
    symbol: 'XRP',
    sign: '✕',
    image: 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ADA',
    sign: '₳',
    image: 'https://cryptologos.cc/logos/cardano-ada-logo.png',
  },
  {
    id: 'binance-coin',
    name: 'Binance Coin',
    symbol: 'BNB',
    sign: 'B',
    image: 'https://cryptologos.cc/logos/bnb-bnb-logo.png',
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'DOGE',
    sign: 'Ð',
    image: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
  },
  {
    id: 'sui',
    name: 'Sui',
    symbol: 'SUI',
    sign: 'S',
    image: 'https://cryptologos.cc/logos/sui-sui-logo.png',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    sign: '●',
    image: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png',
  },
];
